execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_-_test3_est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
execute if score @s TickCount matches 0..940 run function artist_test3est:easy_lvl_1
